### PR TITLE
1/3

### PR DESCRIPTION
**Pull request by shawe**
Added support for time-picker

I am targeting this branch, because {reason}.

In case of bug fix, `3.x` **MUST** be targeted.

Closes #{put_issue_number_here}

## Changelog

```markdown
### Added
- Added some `Class::newMethod` to do great stuff

### Changed

### Deprecated

### Removed

### Fixed

### Security
```

## To do

- [ ] Update the tests
- [ ] Update the documentation
- [ ] Add an upgrade note

### CODE REVIEW

**Comment by greg0ire** [comment]
Why did you do 3 PRs for this? I think you might have misinterpreted some things in CONTRIBUTING.md

**Comment by Soullivaneuh** [comment]
This PR (and the 3 other) completely ignore the contibuting rules of sonata.

I'm closing those one. Feel free to open another(s ?) after [reading the guidelines](https://github.com/sonata-project/SonataCoreBundle/blob/3.x/CONTRIBUTING.md).

**Comment by shawe** [comment]
This reason "This pull request is closed, but the shawe:patch-4 branch has unmerged commits." is not true, I do the pull request manually from github web, @Soullivaneuh can you be more explicitly what is needed for review this changes?

- Add test? Based on CONTRIBUTING.md I understand that this is the one reason.
- All in one commit?
- ...

I can do the changes that the team need for review it, but this is my first time trying to contribute to a big project, and is not as easy as it seems, I only need a little explanation, this must not happend again.

**Comment by greg0ire** [comment]
> I do the pull request manually from github web

please don't. As soon as you touch several files, it's not great. Please 

1. do one commit, with a good message;
2. target 3.x, you got that right, stick with it;
3. give a changelog directed at end users;
4. and if you can, write some unit tests for the php class.

You are literally the first guy here that does numbered PRs like that, and it's a bit baffling to see you wondering about what is wrong exactly, to be perfectly honest with you.

**Comment by shawe** [comment]
@greg0ire thanks for your reply, I will re-do the pull-request.

Maybe here is the first time, but in a lot of others projects (not based on Symfony), I can see this way. Yes is a very dirty way, but easly and quickly way, and at least is a contribution.

**Comment by greg0ire** [comment]
Thanks a lot for your contribution! Please bear with us, we can't afford the dirty way because we have lots of PRs. Thanks for understanding.

**Comment by shawe** [comment]
@greg0ire of course that I understand the really reason, I'm totally agree with that, the only problem is that I'm starting reading seriously about Symfony one month ago, and for me at this moment it's a hard level, and I've intention to change this in some month, but I need to learn a little bit slowly than I'm really doing ;)

As soon as possible as I can, I will try to do a clean pull-request and more respectful with the contribution guidelines. And don't worry about close it again, but please, help a little to new people with less experience.

Thanks for all the team for this work.

**Comment by OskarStark** [comment]
Thank you for your understanding @shawe 👍

**Pull request closed without merging**
