### PR TITLE
Fixed a typo in BasePickerType

### PR DESCRIPTION
**Pull request by RomainSanchez**
I am targetting this branch, because it is a typo

### CODE REVIEW

**Comment by OskarStark** [comment]
Thank you @RomainSanchez, will merge after travis finished his job 👍

**Comment by RomainSanchez** [comment]
What is the point of the pedantic label ?

**Comment by greg0ire** [comment]
It means it does not warrant a release or a changelog.

**Comment by RomainSanchez** [comment]
ok

**Comment by greg0ire** [comment]
(but rest assured this change is very welcome)

**Pull request merged**
