### PR TITLE
Twig deprecation message

### PR DESCRIPTION
**Pull request by ruslan-polutsygan**
fixes this issue https://github.com/sonata-project/SonataCoreBundle/issues/203

### CODE REVIEW

**Comment by rande** [comment]
This interface is 18 days old: https://github.com/twigphp/Twig/commit/e3a325f249a5ff4cdbbabbec7271c13dee2d7ac5#diff-3b09a7e7f6b3d1a99d4a932e14a9ddae ... Seems you need to update ``composer.json`` to be sure the twig@v1.23.1  is installed

**Comment by Soullivaneuh** [comment]
> This interface is 18 days old: twigphp/Twig@e3a325f#diff-3b09a7e7f6b3d1a99d4a932e14a9ddae ... Seems you need to update composer.json to be sure the twig@v1.23.1 is installed

If older version are incompatible, the `composer.json` file should be updated too. :-)

**Comment by rande** [comment]
@Soullivaneuh I think it is compatible, you just get a new deprecated warning from symfony ;)

**Comment by ruslan-polutsygan** [comment]
requried twig version updated

**Comment by rande** [comment]
The composer should include `~1.23,>=1.23.1`

**Comment by ruslan-polutsygan** [comment]
@rande That interface exists since 1.23.0 https://github.com/twigphp/Twig/blob/v1.23.0/lib/Twig/Extension/GlobalsInterface.php
Why requried version should start from 1.23.1?

**Comment by rande** [comment]
correct!

**Comment by Soullivaneuh** [comment]
> The composer should include `~1.23,>=1.23.1`

In this case, `^1.23.1`. :+1:

**Comment by ruslan-polutsygan** [comment]
@rande  is it OK for merge now?

**Comment by ruslan-polutsygan** [comment]
@rande thanks

**Pull request merged**
