### PR TITLE
Update config twig form -> twig form_themes

### PR DESCRIPTION
**Pull request by pierre-H**
I am targeting this branch, because it's the last one.

### CODE REVIEW

**Comment by greg0ire** [comment]
Please write a changelog directed at end users. Keep in mind that they probably do not care what file or class you changed, but what features you provided / what bugs you fixed. Try to answer the question "What benefit do I get from upgrading?"
More on http://keepachangelog.com

**Comment by greg0ire** [comment]
I removed the changelog, it is not needed for docs PRs

**Comment by greg0ire** [comment]
> I am targeting this branch, because it's the last one.

That's not a good reason.

**Comment by greg0ire** [comment]
I removed the todo list, because you have nothing left to do code-wise.

**Comment by greg0ire** [comment]
Please kindly squash your commits together. If you don't, we'll try to remember to do it for you but it's best if you save us this trouble.

How to do that?

1. `git rebase -i origin/3.x`, assuming `origin` is a git remote that points to this repository, and not your fork. If you're not sure what your remotes are, run `git remote -vvv`, there should be your fork and the holy/reference/base/origin/whatever-you-call-it repository.
2. A window will show up with many lines, replace `pick` with `fixup` on every line but the first one
3. Close your editor, git should do its magic, and you should end up with one commit
4. Use `git push --force` to overwrite what you already pushed. Don't forget the `--force` option otherwise git will try to merge both things together.

**Comment by greg0ire** [comment]
1. Fetch all new commits: `git fetch --all`. ⬇️ 
2. Rebase on what you fetched interactively: ✂️ 
    1. `git rebase -i origin/3.x`, assuming `origin` is a git remote that points to this repository, and not your fork. If you're not sure what your remotes are, run `git remote -vvv`, there should be your fork and the holy/reference/base/origin repository.
    2. A window will show up with many lines, remove every line but the last one, which should correspond to your commit.
   2. If you run into a conflict: 💥 
        1. fix it with `git mergetool`. 😷 
        1. continue on your merry way with `git rebase --continue`. ⏩ 
3. Force push to overwrite all this : `git push --force`. ⬆️

**Comment by OskarStark** [comment]
@pierre-H can you please rebase your PR?

**Comment by OskarStark** [comment]
ping @pierre-H

**Comment by pierre-H** [comment]
I tried the @greg0ire and it didn't work as excepted (I don't know why).
You can close this pull request and do another one with the fix.

**Comment by OskarStark** [comment]
can you check, if this checkbox is activated in your PR here?
screenshot 2017-08-25 08 44 10

If yes, I can support you

**Comment by pierre-H** [comment]
@OskarStark yes it's checked

**Comment by OskarStark** [comment]
strange, can you please give we write access to your forked repo?

**Comment by OskarStark** [comment]
Thank you @pierre-H 👍

**Comment by pierre-H** [comment]
Thanks to your great job @OskarStark

**Pull request merged**
