### PR TITLE
Fix fatal error related to missing retrurn statement in FlashMessageExtension

### PR DESCRIPTION
**Pull request by tifabien**
## Subject

I am targeting this branch, because it fixes a fatal error.

## Changelog

```markdown
### Fixed
 - Fixed a missing return statement in FlashMessageExtension
```

### CODE REVIEW

**Comment by andreypaa** [comment]
After this fix - a new error :
Unable to load the "Sonata\Twig\Extension\FlashMessageRuntime" runtime.

**Comment by OskarStark** [comment]
ping @core23

**Comment by tifabien** [comment]
@andreypaa weird I don't have this error.

**Comment by OskarStark** [comment]
I asked for a release

**Comment by GalloisLuca** [comment]
thanks for the future release, i was looking for the error for 2 hours

**Comment by greg0ire** [comment]
See https://github.com/sonata-project/SonataCoreBundle/pull/605

**Comment by greg0ire** [comment]
@tifabien I used another changelog message as the one you provided, something less technical, more functional.

**Comment by gremo** [comment]
Even updating to 3.13.1
> Unable to load the "Sonata\Twig\Extension\FlashMessageRuntime" runtime.

**Pull request merged**
