### PR TITLE
correct datepicker input wrapper class

### PR DESCRIPTION
**Pull request by mcwebb**
The datepicker wrapper class was erroneously set as "form-control" this caused issues with help blocks and other elements.

### CODE REVIEW

**Comment by jcrombez** [comment]
I had to override the whole template for my current project to achieve this.
A merge would be nice :+1:

**Comment by OskarStark** [comment]
ping @core23

**Comment by core23** [comment]
Looks okay to me

**Comment by OskarStark** [comment]
thank you @mcwebb

**Comment by mcwebb** [comment]
:+1:

**Pull request merged**
