### PR TITLE
Added missing datepicker options

### LINKED ISSUE #373: Eonasdan datepicker missing options
Hi, i wanted to know if there is any plan to add the missing options (like viewMode, inline, ...) for the datepicker to `BasePickerType`. 

I am willing to do it myself and make a PR if needed.

May be related to #149 

http://eonasdan.github.io/bootstrap-datetimepicker/Options/

### PR DESCRIPTION
**Pull request by RomainSanchez**
I am targeting this branch, because the changes are backwards compatible.

Closes #373

## Changelog

```markdown
### Added
- Missing bootstrap datepicker options (`dp_collapse`, `dp_calendar_weeks`, `dp_view_mode`)

### CODE REVIEW

**Comment by greg0ire** [comment]
No docs needed?

**Comment by RomainSanchez** [comment]
> No docs needed?

Didn't think so as the options are documented here: http://eonasdan.github.io/bootstrap-datetimepicker/Options/ and i didn't see anything about the other options in the existing doc

**Comment by OskarStark** [comment]
Could you please add a test for the new options?

**Comment by greg0ire** [comment]
There is [a code block](https://github.com/sonata-project/SonataCoreBundle/blob/b91e10522df71ff6dec57697d91df23a3929f1f4/Resources/doc/reference/form_types.rst) with `dp_` options, please add yours so that people know what is supported (don't have them guess).

**Comment by RomainSanchez** [comment]
```php
foreach ($view->vars['dp_options'] as $dpKey => $dpValue) {
            $this->assertFalse(strpos($dpKey, '_'));
            $this->assertFalse(strpos($dpKey, 'dp_'));
        }
```
The existing test just asserts that the options were camelized properly and had the dp_ prefix removed so it applies to the new options as well.

are there any other assertions that sould be added ?

**Comment by greg0ire** [comment]
> are there any other assertions that sould be added ?

I don't think there is anything of value to test here.

**Comment by RomainSanchez** [comment]
> There is a code block with dp_ options, please add yours so that people know what is supported (don't have them guess).

The block only contains a few options for example purposes should i make it the full list of available options or just add the ones added in this PR

**Comment by greg0ire** [comment]
> The block only contains a few options for example purposes should i make it the full list of available options or just add the ones added in this PR

You MUST add the ones added in the PR. You MAY add more in a separate commit after that (`git add -p` is your friend).

MUST and MAY are defined in https://tools.ietf.org/html/rfc2119

**Comment by RomainSanchez** [comment]
Anything else required before merge ?

**Comment by OskarStark** [comment]
> Anything else required before merge ?

No, thank you! 👍

**Pull request merged**
