### PR TITLE
3.10.0

### PR DESCRIPTION
**Pull request by greg0ire**
Please approve and rebase

### CODE REVIEW

**Comment by OskarStark** [comment]
Thank you @greg0ire

**Comment by kunicmarko20** [comment]
I think he has to merge? or does he 🤔

**Comment by greg0ire** [comment]
No label needed, and rebase means rebase :P

**Comment by greg0ire** [comment]
Hmmm, weirdly, this created a new commit, when it should have been a fast-forward… strange.

**Pull request merged**
