### PR TITLE
Optimized WidgetTestCase

### PR DESCRIPTION
**Pull request by core23**
I am targetting this branch, because this is BC (we have no tag since #275).

## Changelog

```markdown
### Added
- added `AbstractWidgetTestCase::getEnvironment` method
- added `AbstractWidgetTestCase::getRenderingEngine` method

### Removed
- removed `AbstractWidgetTestCase::getTwigExtensions` method
```

## Subject

Updated the `AbstractWidgetTestCase`, so we can extend this class in https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Tests/Form/Widget/BaseWidgetTest.php

### CODE REVIEW

**Comment by greg0ire** [comment]
Can you find a better commit message?

If I read the diff, I'd say you add more methods (more extension points) to ease the override.

**Comment by core23** [comment]
That's right. I changed the API for this class.

**Comment by greg0ire** [comment]
Looks better :)

**Comment by greg0ire** [comment]
LGTM

**Comment by OskarStark** [comment]
Thank you @core23 👍

**Pull request merged**
