### PR TITLE
Update bootstrap to version 3.3.6.

### PR DESCRIPTION
**Pull request by tim96**
Update bootstrap to version 3.3.6.

### CODE REVIEW

**Comment by OskarStark** [comment]
LGTM 👍

**Comment by OskarStark** [comment]
ping @greg0ire

**Comment by OskarStark** [comment]
Thank you @greg0ire , thank you @tim96

**Comment by Soullivaneuh** [comment]
Its a patch upgrade of a vendor. Considering this as a patch so.

**Pull request merged**
