### PR TITLE
Merge 3.x

### PR DESCRIPTION
**Pull request by core23**
Manual merge of 3.x into the master branch.

### CODE REVIEW

**Comment by greg0ire** [comment]
There are conflicts. If you want to do this, you have to create a new branch from master, merge 3.x in that, resolve the conflicts, and make a PR from that.

**Comment by core23** [comment]
Fixed the conflicts 👍 

> If you want to do this, you have to create a new branch from master, merge 3.x in that, resolve the conflicts, and make a PR from that.

That's what I've done.

**Comment by core23** [comment]
Your PR https://github.com/sonata-project/SonataCoreBundle/pull/356 has made some problems. Next time we should merge the stable branch into the master before removing deprecated stuff.

**Comment by greg0ire** [comment]
The problem is that there will always be new things on master, so I think the right thing to do is to merge regularly, so as not to have a gazillion conflicts to change each time. That or wait the last moment before removing deprecated stuff…

**Comment by core23** [comment]
> The problem is that there will always be new things on master

That's right, but there were 25 commits which is very annoying. We should find a way to notify us via slack, if the `dev-kit` can't merge it.

**Comment by greg0ire** [comment]
@Soullivaneuh please review this. Since you're the one who does these merges usually…

**Pull request merged**
