### PR TITLE
REMOVE unnecessary transliteration.

### PR DESCRIPTION
**Pull request by chigix**
Signed-off-by: Richard Lea <chigix@zoho.com>

### CODE REVIEW

**Comment by chigix** [comment]
1. This transliteration would occurs unexcepting notice for some characters like chinese and japanese, which would make twig throw exception.
2. The following includes a `preg_replace` to remove unwanted characters.

**Comment by Soullivaneuh** [comment]
Tests seems to fail.

@rande what do you think of this PR? Don't really know the utility of iconv here.

**Comment by chigix** [comment]
It's my missing on the fix of corresponding code in testing.

**Comment by Soullivaneuh** [comment]
@chigix https://travis-ci.org/sonata-project/SonataCoreBundle/jobs/62518871#L346

Test case should not be adapted IMO, the expected value should not change.

**Comment by rande** [comment]
This is some old legacy code, most sonata's bundles now use cocur's slugify library (but not by default to avoid BC break). So I think the service should be adapted to accept a configuration setting to used cocur's slugify library

**Comment by OskarStark** [comment]
Any news on this PR?

**Comment by chigix** [comment]
Through this disscussion, I'm also very confused that if the slugify provided in SonataCore is to be deprecated? If not, then how to deal with the legacy code which is hard to understand? Sincerely, completing this code in method and testing, rebase commitment is not the main challenge, I think.

**Comment by OskarStark** [comment]
ping @rande

**Comment by rande** [comment]
We need to keep this code as it used in other component. However you can send a new PR based on SonataPageBundle code: https://github.com/sonata-project/SonataPageBundle/blob/master/SonataPageBundle.php#L42-L64

Also this PR need to be rebased.

**Comment by chigix** [comment]
So what should do to deal with the failed testing with the error from the tranliteration? The `iconv` usage previously is not compatible with the characters out of alphabetics, such as Chinese and Japanese, which is the primary focus in this PR. But the remove on this `iconv` code would not be passed through the preset testing code. So I was thinking that testing code should also be modified to adapted this case, right?

**Comment by Koc** [comment]
covered by #214 and can be closed IMHO

**Comment by OskarStark** [comment]
:+1: @Koc

**Pull request closed without merging**
