### PR TITLE
Extract form and twig to extensions - CoreBundle v3.20

### PR DESCRIPTION
**Pull request by wbloszyk**
## Subject

Extract form and twig to be load from seperated repository.

I am targeting this branch, because this PR respect BC.

Part of #741 

## Changelog

```markdown
### Removed
- remove form and twig directory from CoreBundle and force to install this files from form-extensions 0.x and twig-extensions 0.x
```

## TODO
- [x] #751 and release as 3.19.x
- [x] https://github.com/sonata-project/form-extensions/pull/92 and release as 0.1
- [x] https://github.com/sonata-project/twig-extensions/pull/80 and release as 0.1

### CODE REVIEW

**Comment by VincentLanglet** [comment]
There is a lot of file removal.

If I understand correctly each of the removed file find can be found in the form-extension or twig-extension with the same namespace and the exact same code. This is pretty hard to check...

I'm requiring only `SonataAdminBundle` in project. So If I run composer upgrade it will automatically update SonataCoreBundle. I'm certainly not the only one.
And now SonataCoreBundle require a beta of  sonata-project/form-extensions and  sonata-project/twig-extensions. If we require "^0.1", it theorically can add a BC-break with any upgrade. We have to fix `0.1.*` instead.

Does a 3.20.beta release would be enough for the start of the CoreBundle-removal plan ?

WDYT @sonata-project/contributors

**Comment by wbloszyk** [comment]
CoreBundle removal plan start in 3.19
3.19.1 - fix flashmessage configuration
3.19.2 - fix alias from other bundle - allow register bridges with core

It means you don't have to register CoreBundle in 3.19.2.

If checking removal it to hard you can copy form  directory from CoreBundle to form-extensions 0.x branch (composer.json should be the same). For twig too. I merge some change from 1.x branch but i can add it after replace.

Extensions branch 0.x should be use for drop CoreBundle. Then should be upgrade to 1.x. 

If you have questions please let me know.

**Comment by wbloszyk** [comment]
@VincentLanglet 
> Does a 3.20.beta release would be enough for the start of the CoreBundle-removal plan ?

In Step 3 of make CoreBundle optional i will replace SonataCoreBundle by extensions 0.x || 1.x. `CoreBundle <3.20` will be add to conflict. This mean we can release this as beta but this will not allow install feature sonata-project bundles releases in project with CoreBundle as long as we release it as stable 3.20. 

BTW, Extensions 0.x should not be maintained and should be trait as part of SonataCoreBundle.

**Review by core23 — DISMISSED** [review]

**Comment by wbloszyk** [comment]
@core23 WDYT Can we change translations from SonataCoreBundle to SonataFormBundle for form?

**Comment by wbloszyk** [comment]
@greg0ire RTM

**Review by jordisala1991 — APPROVED** [review]

**Comment by jordisala1991** [comment]
Probably getting more reviews would be better, it's a lot of removal. I think it looks good

**Review by core23 — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks @wbloszyk ! I'm working on a release!

**Comment by VincentLanglet** [comment]
I think something is wrong @wbloszyk 
cf https://github.com/sonata-project/form-extensions/issues/98

**Pull request merged**
