### PR TITLE
Fix typo introduced in #238 (2.x branch)

### PR DESCRIPTION
**Pull request by fracsi**
Fixes: #241 in 2.x branch

### CODE REVIEW

**Comment by greg0ire** [comment]
I'll probably squash and merge and change the commit message, but you should read that anyway : https://github.com/Soullivaneuh/sonata-dev-kit/blob/doc-contributing/doc/CONTRIBUTING.md#the-commit-message

**Comment by fracsi** [comment]
@greg0ire Thanks. These were my first PRs on sonata.

**Comment by Soullivaneuh** [comment]
@fracsi Next time you see an issue on the latest stable version, just PR on the stable branch (2.x on this case). All fixes will be backported to master in any way. :+1:

**Comment by greg0ire** [comment]
Thanks @fracsi

**Pull request merged**
