### PR TITLE
Return FQCN for SF2.8+ and text type for >2.8

### PR DESCRIPTION
**Pull request by ethernal**
I was editing in the browser - can't do much from work as we are locked behind proxy that's where the errors come from. I did try to squash commits and I can see that it did that locally, but when I synced it with GitHub app I can still see 9 commits to merge. What am I doing wrong

### CODE REVIEW

**Comment by ethernal** [comment]
@greg0ire sorry for the mess. I was unable to push the squashed commits into the branch, not sure what I was doing wrong. I've redone all of it fresh and now it's in a single commit.
Hope this fixes most deprecation messages now.

**Comment by greg0ire** [comment]
Please run make cs, and commit amend your commit with the result.

**Comment by greg0ire** [comment]
The build also fails because the `getParent()` methods are tested (for the sake of code coverage ?). @core23 @OskarStark @Soullivaneuh what do you think? Should @ethernal change the tests? Or simply remove them?

**Comment by Soullivaneuh** [comment]
:+1: For tests changes.

**Pull request closed without merging**
