### PR TITLE
Manual merge

### PR DESCRIPTION
**Pull request by greg0ire**
I think that was (or is, not sure it is correct/finished yet) one of the hardest merges of my life :sweat_smile:

### CODE REVIEW

**Comment by OskarStark** [comment]
And travis is failing 😢

**Comment by greg0ire** [comment]
Yes, let's try again with phpunit 7 :P

**Comment by greg0ire** [comment]
Another attempt, in which I also cleanup Doctrine related stuff

**Comment by greg0ire** [comment]
Green!

**Pull request merged**
