### PR TITLE
Sort packages

### PR DESCRIPTION
**Pull request by greg0ire**
I am targetting this branch, because this is BC

## Subject

This reduces conflict risks and naturally groups packages by vendor.

### CODE REVIEW

**Comment by greg0ire** [comment]
Not a patch, so… minor ?

**Comment by Soullivaneuh** [comment]
Just pedantic. Why do you absolutely want to add another one? :stuck_out_tongue:

**Comment by Soullivaneuh** [comment]
RTM. :+1:

**Comment by greg0ire** [comment]
> Just pedantic. Why do you absolutely want to add another one? :stuck_out_tongue:

Oh right, my bad…

**Pull request merged**
