### PR TITLE
Remove deprecated code

### PR DESCRIPTION
**Pull request by OskarStark**
I am targeting this branch, because this renamed already deprecated variables.

Refs #390

### CODE REVIEW

**Comment by greg0ire** [comment]
Renaming variables is BC, right? Why not do it on 3.x?

**Comment by OskarStark** [comment]
I thought would be better like this, as I introduced a NEXT_MAJOR in #390 and you guys approved it 😄

**Comment by greg0ire** [comment]
Yup, sorry, didn't realise it was fully BC until I saw your `minor` tag

**Comment by OskarStark** [comment]
No Problem, so how do we proceed? Shall I do it against `3.x`?

**Comment by OskarStark** [comment]
done @greg0ire

**Comment by greg0ire** [comment]
I think this is in fact pedantic : there is zero impact to the user

**Comment by OskarStark** [comment]
> I think this is in fact pedantic : there is zero impact to the user

I marked it as pedantic, but keep the changelog

**Comment by greg0ire** [comment]
> but keep the changelog

Why?

**Comment by OskarStark** [comment]
Ok

**Comment by jordisala1991** [comment]
Thanks @OskarStark

**Pull request merged**
