### PR TITLE
Use the correct Writer for Excel files

### PR DESCRIPTION
**Pull request by lyoshenka**
Despite being called `XlsWriter`, it does not output Excel-formatted files. Instead it outputs HTML tables. I believe the correct class is `XmlExcelWriter`.

### CODE REVIEW

**Comment by OskarStark** [comment]
ping @rande

**Comment by rande** [comment]
Depends on which version of office you like to support. XML version if for xlsx format. The html version works with any version of office.

**Comment by rande** [comment]
Office 2016 on mac warns users which 2 modals with the current ``XlsWriter``. Maybe it is the time to change. I will prefer to have a new format in the ``xlsx`` then. So we are BC with the code. This need applied on the SonataAdminBundle too.

**Comment by Soullivaneuh** [comment]
> I will prefer to have a new format in the xlsx then. So we are BC with the code. This need applied on the SonataAdminBundle too.

:+1:

**Comment by Soullivaneuh** [comment]
I put it as major but not sure. ping @sonata-project/contributors

**Comment by greg0ire** [comment]
It's BC with the code. It it breaks something for a user, they will fix it by making a PR, but they will still not change their code, will they? I would tag this as minor.

**Comment by core23** [comment]
Can't we use a config key for this? So the user could choose between XLS and XLSX

**Comment by Soullivaneuh** [comment]
> Can't we use a config key for this? So the user could choose between XLS and XLSX

I was thinking about that to. @lyoshenka could you please take a look?

**Comment by lyoshenka** [comment]
Sorry, it's been a while. What would you like me to look at?

**Comment by greg0ire** [comment]
We would like you to develop a configuration key that would default to the writer for `xlsx`, but would allow to choose the writer for `xls`. Would you be ok to develop that? If yes, do you need some guidance?

**Comment by lyoshenka** [comment]
Yea, I'm happy to do that. What's a configuration key?

**Comment by greg0ire** [comment]
[This](https://symfony.com/doc/2.7/cookbook/bundles/configuration.html#main) is what we are taking about.

**Comment by Soullivaneuh** [comment]
Changing to minor after @greg0ire comment.

**Comment by Soullivaneuh** [comment]
According to the new [Sonata version management](https://github.com/sonata-project/SonataAdminBundle/issues/3053) and next major [release plan](https://github.com/sonata-project/SonataAdminBundle/issues/3731), this project has been refactored regarding branching and versioning.

If you see this message, your PR concerns a patch or a minor release and is not targeting the right branch.

So I'm closing this one, but don't see it as a refusal. If you think your work is still relevant and want to continue, feel free to reopen it on the right branch (e.g. the default one).

Regards.

**Pull request closed without merging**
